// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeCartServiceServer is an autogenerated mock type for the UnsafeCartServiceServer type
type UnsafeCartServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedCartServiceServer provides a mock function with given fields:
func (_m *UnsafeCartServiceServer) mustEmbedUnimplementedCartServiceServer() {
	_m.Called()
}
